-- 240_drop_custom_endpoints_setting.sql
--
-- 批次 6 / 包 D：删掉「站点设置」卡片里的自定义端点列表（custom_endpoints）。
--
-- 背景：这项设置让站长在后台额外填几条 API 端点地址，用户在「API Keys」页
-- 可以一键复制。单管理员内部部署下只有当前站点这一个入口，生产上该键的值
-- 自上线起一直是空数组 []，从未有人填过；与它相邻的 api_base_url 早在批次 2
-- 就已删除。站长已确认整体删除：前端卡片与 Keys 页的自定义端点渲染、后端
-- 读写校验、公开设置输出与默认种子里的键一并移除，Keys 页只保留当前站点
-- origin 这一条内置端点（复制 / 测速按钮照旧）。
--
-- 幂等：DELETE 不存在的键无副作用，重复执行只是再删一次空集。
DELETE FROM settings WHERE key = 'custom_endpoints';
